### ISSUE TITLE
XpListPreferenceDialogFragment.mPreference leaks hosting Activity

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#100]
Can you please look into this?

net.xpece.android:support-preference:1.3.2

![image](https://user-images.githubusercontent.com/6302839/37983046-8743c264-31f2-11e8-9ad3-e4b440e9a48d.png)

Thank you.

**Comment by consp1racy** [comment]
I can try. Where did this happen? What version of Android, what device?

**Comment by dirkam** [comment]
Sorry for not providing this basic info in the first place.
Pixel XL, 8.1
I can't always reproduce it, but I'm not sure I'm aware of the exact repro steps. However, Leak Canary reported this multiple times.
Open the settings screen of the app. Open a ListPreference. Try to navigate back to the main activity quickly.

**Comment by consp1racy** [comment]
Do you set `retainInstance = true` in your settings fragment?

`PreferenceFragment` wasn't built with retaining in mind. I'm afraid I can't fix that, since the leak comes from the support library.

If you decide to use non-retained fragment, it may make your life harder if you use non-persistable preferences. You're responsible for storing non-persistable preference values.

Is this your case?

---

Using non-retained fragment will cause the preference hierarchy to reinflate on each configuration change, which sucks. 

I'll look for a way how to have the list adapter and preference manager use application context. And Activity context should only be used when creating and binding view holders.

**Comment by consp1racy** [comment]
The list adapter is already set up in way that it takes context from the recycler view, which is recreated with correct activity theme.

So the only thing we need is to make the preference manager with application context.

I'll get back with more info.

**Comment by dirkam** [comment]
I double checked and I don't set retainInstance.

**Comment by consp1racy** [comment]
Ok, looks like it's because of SeekBarPreference, do you use this one?

To be able to update "info" text field in real time while dragging the seek bar I needed to track bound info text views. That's done here:

    public class SeekBarPreference extends Preference {
        // A filthy hack so we can update info text while dragging seek bar thumb.
        private static final WeakHashMap<TextView, SeekBarPreference> mInfoViews;
    }

That's actually wrong. WeakHashMap values are strongly referenced, so that SeekBarPreference that holds onto a Context keeps it from being garbage collected.

<s>I managed to fix it like this:

    private final Set<TextView> mInfoViews = Collections.newSetFromMap(new WeakHashMap<TextView, Boolean>());

</s>

The fix is to use a weak hash map of weak hash sets.

Unfortunately this doesn't have a workaround on client side, so you'll have to wait for next release.

**Comment by dirkam** [comment]
I do use SeekBarPreference. Thanks for the fix.

**Comment by consp1racy** [comment]
This was fixed in commit 07d62a1 and will be part of next release.
