### ISSUE TITLE
Verify and ensure compatibility with jetpack 1.0.0

### ISSUE THREAD

**Issue by consp1racy** [consp1racy/android-support-preference#108]
- [x] Proguard rules
- [x] Default preference packages
- [x] No custom classes in android.support.* packages
- [x] Remove AspCheckedTextView and AspSwitchCompat

**Comment by anggrayudi** [comment]
Well, I think we need to publish this library with AndroidX Jetpack ASAP. I checked so many dependencies on my project, and found that 3 of 19 dependencies are still using old Support Library. Support Preference is one of them. I am aware that this lib will cause crash to my app since Support Library has different package name with AndroidX Jetpack. We don't have to wait until stable version `1.0.0` is released by Google. We can do it now. I have tested AndroidX and found no problem with it.

**Comment by consp1racy** [comment]
When you turn on jetifier all support library dependencies will be rewritten to AndroidX. Then you can update individual AndroidX dependencies in your project.

https://developer.android.com/jetpack/androidx/migrate

I tested it half a year ago and it worked just fine.

**Comment by ghost** [comment]
Hi,
I tried to update the gradle dependencies as described [here](https://github.com/consp1racy/android-support-preference/tree/3.x-dev#how-to-get-the-preference-library) but had the following error:
"Failed to resolve: net.xpece.android:support-preference:3.0.0".
Is there any way to use the version 3.0 right now?

**Comment by consp1racy** [comment]
Hi, v3 is a work in progress. If you still want to try it you can grab the branch from jitpack.io.

Other than that you should be fine with v2. With enabled jetifier.
