### ISSUE TITLE
Error:(2) Attribute "key" has already been defined

### ISSUE THREAD

**Issue by chongbo2013** [consp1racy/android-support-preference#12]
Error:(2) Attribute "key" has already been defined
i can't import the project.

**Comment by consp1racy** [comment]
Hi, this is because the preference-v7 library defines all preference related android prefixed attributes also in the app namespace.
In addition to `android:key` you have `app:key` as well. Which is pretty much useless because native preference attributes are available on all platforms supported by preference-v7 library.
This unfortunately has a nasty side effect that **no one else can define attributes with the same name**.

Your options:
1. If you're using another library which was similarly stupid (instead of using `android:key` is using `app:key`) you would need to drop it.
2. If this attribute is defined within your project you can just change it. See `attr.xml` in the library sources.

My options:
1. Push support library developers to drop these nonsensical attrs in next release of their library.
2. Straightup copy preference-v7 library to my project. I'd have to think about that.

**Comment by chongbo2013** [comment]
Thank you very much, though not yet been solved

**Comment by xufeifandj** [comment]
Hey, brothers .are you going to  to drop these nonsensical attrs in next release of their library,

**Comment by xufeifandj** [comment]
I always pay attention to your project

**Comment by consp1racy** [comment]
I'm not dropping preference-v7 dependency. Other libs are going to have to learn to prefix their attributes or use platform attributes when applicable.
