### ISSUE TITLE
EditTextPreference not working with android:inputType="numberDecimal"

### ISSUE THREAD

**Issue by almkhaj** [consp1racy/android-support-preference#34]
Hi,
EditTextPreference not working with android:inputType="numberDecimal"

**Comment by consp1racy** [comment]
### Issue

`EditTextPreference` cannot pass any attributes to its `EditText` because both are created at different times with different context (one in activity, one in dialog). Sadly it's not possible to retain raw attributes after `EditTextPreference` finishes inflating for later use.

### Solution

After inflating your preference XML get a reference to your `EditTextPreference` and assign a `OnEditTextCreatedListener` to it. There you can setup your `EditText` reliably.

```
EditTextPreference pref = (EditTextPreference) findPreference("key");
pref.setOnEditTextCreatedListener(new OnEditTextCreatedListener() {
    @Override
    public void onEditTextCreated(EditText edit) {
        edit.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);
    }
});
```

Source: https://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType

**Comment by almkhaj** [comment]
Perfect solution! Thank you for your great library
