### ISSUE TITLE
Extra dependencies for Preferences

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#54]
With the basic preferences the only dependency we can use is a `CheckBoxPreference`. In many cases it would be great to define the dependencies in XML for other types as well.

A few examples:
Dependency for `ListPreference` value (e.g. `android:dependency="myListPreference:MYVALUE"`)
Dependency for `EditTextPreference` value (e.g. checking for empty state `android:dependency="myEditTextPreference:null"`)

Not sure if this is possible but I believe that it would be very useful. Obviously you can do this in code as well but it would save a lot of time and effort to just define these in XML.

**Comment by consp1racy** [comment]
Couple of issues off the top of my head:
 - How to specify multiple values?
 - Treat empty string as null?
 - Disable dependent items or hide them?
 - `android:dependency` is handled by framework; would need a new attribute.
 - Need for parser.

I don't think it's worth investing time and effort into such feature as not many would benefit from it. Solving this in Java will IMO allow better readability and performance.

**Comment by dirkam** [comment]
Don't know how much effort this requires, but I for sure would be very happy to handle these from XML.
I understand that there are a lot of questions, this was just a basic idea.

_How to specify multiple values?_
This is only applicable to multi select preferences, normal `ListPreference` should be more straightforward I guess.
_Treat empty string as null?_
Or check for length or something.
_Disable dependent items or hide them?_
`android:dependency` disables the item, hiding could be an option.
_android:dependency is handled by framework; would need a new attribute._
You mean `asp:dependency` or something? I wouldn't mind using it at all.

Thanks for considering it, maybe others can comment on this as well.

**Comment by consp1racy** [comment]
I'll leave this open for input. Won't implement it for now.

**Comment by consp1racy** [comment]
### Ideology

I've ultimately decided against this idea, because it goes against the main goals of this library
 - to provide bridge between preference-v7 and appcompat-v7
 - to introduce missing elements from Material design

In a few words: this library is what I imagined preference-v7 would be in the first place. This library shouldn't need to exist.

Introducing proposed behavior would divert in major way from framework and introduce unnecessary complexity.

### Implementation

More ideas:
 * How to specify multiple values?
   * Okay, let's stick with multi select list. Values for multi select list view are provided by a string array resource. There is no way to reuse that simply, so I need a parser for resource references.
   * What about edit text preference? There are infinite possibilites. So now I need a regex parser too.
 * Null string.
   * "Check the length or something" sounds pretty vague and has no informational value. I know how to check if a string is null or empty or neither. It's a question of semantics. Do we treat `null` in a different way than `""`? What if someone else has a different idea/needs from what would be actually implemented. I don't want to lock someone in a ceratain way.
   * We need to distinguish from `null` and `"null"` so the parser has to know about quotes.

And so on, and so forth.

---

*When dealing with this programmatically the consumer (you) can ultimately decide on concrete behavior of their custom dependency system, be agile and adapt quickly to changing needs.*

There is no one best way to implement this. You can express your precise needs way easier in Java than you could ever mash up into one XML attribute.

I appreciate the input but I believe the cost to benefit ratio of such feature is non-existent.

**Comment by dirkam** [comment]
Thanks for elaborating on this.
