### ISSUE TITLE
PreferenceScreen (subscreen) support

### ISSUE THREAD

**Issue by jeppe-style** [consp1racy/android-support-preference#7]
Hi,

Thanks for a great library!

Do you have any plans to support subscreens with icon tinting and having the action bar show on the subscreen in the near future?

**Comment by consp1racy** [comment]
Hello, can you provide code sample so I can replicate the issue?

**Comment by jeppe-style** [comment]
Sure. If you add the code below to `pref_general.xml` in your sample app, then you see that the icon on the `PreferenceScreen` is not tinted, and that there is no actionbar when the you click to display the subscreen. Ideally, at least in my case, you would get the title from the subscreen and the back arrow in the actionbar automatically.

Thanks for the quick reply.

``` java
    <PreferenceScreen
        android:key="subs_screen"
        android:title="Subscreen"
        android:persistent="false"
        android:icon="@drawable/ic_ring_volume_black_24dp"
        app:asp_tintIcon="true">

        <CheckBoxPreference
            android:key="example_icon_pref"
            android:title="Icon test"
            android:icon="@drawable/ic_ring_volume_black_24dp"
            app:asp_tintIcon="true"
            />

    </PreferenceScreen>
```

**Comment by consp1racy** [comment]
I see, thank you for pointing this out. This is because the library currently uses native `PreferenceScreen` (with custom layout so text is aligned properly). Currently I can think of two ways to approach this:
1. Subclass `PreferenceScreen` and try to add a toolbar and tinting.
2. Try to replicate `PreferenceGroup` hierarchy.

Option 2 will be better (if it'sdoable) because it looks there are dialogs involved and this would give me opportunity to use AppCompatDialog. I'll look into this.

**Comment by consp1racy** [comment]
Just a quick overview of what I've found so far:
1. `PreferenceScreen` is final, so I can subclass it in order to just add tinting.
2. I started porting the `PreferenceGroup` hierarchy and as suspected it's proving to be a bit of a bitch. `PreferenceScreen` is used on several places directly by `PreferenceManager` which may or may not mean I'll have to backport the whole `android.preference` package instead of cherrypicking what I want. Which also means that I'll closely have to watch changes to this package in future releases of SDK.

Currently I'm working on proxying my `PreferenceScreen` class to system class and vice versa via reflection where applicable. I'll be testing this on monday, I think.

**Comment by jeppe-style** [comment]
thanks for the update and efforts! sounds like 1. is the way better option. let me know if I can be of any help.

**Comment by consp1racy** [comment]
Yes, option 1 would be most awesome, but `PreferenceScreen` is final, so no go.

Looks like I'll have to pull the whole `android.preference` package and maintain it which is exactly what I wanted to avoid. This will take some time.

**Comment by jeppe-style** [comment]
OK. I previously also tried [this library](https://github.com/ferrannp/material-preferences) which implements the subscreen feature (other features are missing), and it looks like he intercepts the click and displays another fragment instead (see [PreferenceFragment.java](https://github.com/ferrannp/material-preferences/blob/master/library/src/main/java/com/fnp/materialpreferences/PreferenceFragment.java)). Maybe an alternative solution?

**Comment by consp1racy** [comment]
Subscreen handling is now implemented in one way as part of the example project.
Maybe in future it may be part of this library.

Beware, the new version 0.5.0 uses preference-v7 as its base instead of native preference which will require you to change some things on your end (mostly just using XpPreferenceFragment instead of AppCompatPreferenceActivity).
